### ISSUE TITLE
connection.Create( ... ) incorrectly inserts existing related objects

### ISSUE THREAD

**Issue by mikehancock** [Paymentsense/Dapper.SimpleSave#12]
when inserting a record, sometimes I want to attach an existing record as part of this insert. Current simple save does not check for the existence of a PK, so just goes ahead and creates a copy of the existing record and attaches the newly created copy. 

I have created a failing test that describes this scenario:

```C#
[Test]
public void insert_with_fk_on_existing_child_no_reference_data_inserts_parent_and_not_child()
{
    var newDto = new ParentDto()
    {
        OneToOneChildDtoWithFk = new OneToOneChildDtoWithFk { ChildKey = 943982 }
     };

    var cache = new DtoMetadataCache();
    var commands = GetCommands(cache, null, newDto, 2, 2, 2, 0, 0, 2, 2, 0, 0);
    var list = new List<BaseCommand>(commands);

    var parentInsert = list[0] as InsertCommand;

    Assert.AreEqual(
        cache.GetMetadataFor(typeof(ParentDto)).TableName,
        parentInsert.Operation.ValueMetadata.TableName,
        "Unexpected parent table name.");

    Assert.That(list.Count, Is.EqualTo(1));
}
```

**Comment by bartread** [comment]
Thanks @mikehancock. Sounds sensible - if the PK property has a non-null value assume the record already exists and create only the FK reference rather than adding a new record.

**Comment by bartread** [comment]
This would also potentially happen with UPDATEs for non-reference data rows.

I've completely hit a dead end because of it now, so what I'm proposing to do is allow the [ReferenceData] attribute to be used on properties such that the type referenced by the property will be treated (only in that context) as reference data.

This means that if, for example, you have PhoneNumberDto and want to be able to save these to do the database, you can still do so but, when used in the context of (say) UserDto, you can still treat them as reference data and not try to save them.

**Comment by bartread** [comment]
OK, this works now that we can decorate properties with the [ReferenceData] attribute, and we have tests in place.

**Comment by bartread** [comment]
PRed into develop and master.
